server:
  port: 8080
spring.datasource.mysql:
    driverClassName: com.mysql.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/cryptos?autoReconnect=true&useSSL=false
    username: root
    autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
